canonical/oai-ran-du-k8s-operator

tests/unit/test_charm.py
tests/unit/test_oai_ran_du_k8s.py

This is a PR towards @Gmerold 's branch related to adding usb mount. Here I separate the unit tests in two files:
- Charm class tests: Here we completely mock the `DUSecurityContext` and `DUUSBVolume` classes. 
- Kubernetes classes tests: Here we test the  `DUSecurityContext` and `DUUSBVolume` classes specifically.
@Gmerold This does not answer the question you had related to mocks but it makes it irrelevant. 
We have different code classes for those two parts of the code, which warrants different test classes as well.

chore: separate tests for charm code from k8s code

---

charmcraft.yaml
src/charm.py
src/charm_config.py
src/templates/du.conf.j2
tests/unit/resources/expected_rfsim_mode_config.conf
tests/unit/test_charm.py
tox.ini

This PR allows for running the DU in the simulation mode.
Simulation mode should be used for automated tests and can be enabled by setting the `simulation-mode` charm config option to `True`.

feat: Adds possibility of running DU in the simulation mode

---

src/charm.py
tests/unit/test_charm_configure.py

When running the DU with a B210, the error `Error: unknown sampling rate 61440000.000000` appeared in the logs. After some quick search, it turns out that this series of radio needs to be run at 3/4 sampling, with the `-E` command-line switch.
This commit hard codes this switch in the charm, as we are only currently testing with the B210 radio. This will need to be exposed as a configuration item in the future, but the way to do so will need proper design.

fix: Use 3/4 sampling with B210

---

src/charm.py

This exposes the simulator port on the Service when running in simulation mode. There are currently no tests for this. Integration tests with the UE would be a good place to test this in the future.

feat: Expose simulator port when running in simulation mode

---

charmcraft.yaml
src/charm.py
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf
tests/unit/test_charm_collect_status.py
tests/unit/test_charm_configure.py

When using `bridge` CNI for Multus, additional route is required to tell the workload which interface should be used for the F1 communication.

fix: Adds F1 route when using bridge CNI

---

charmcraft.yaml
lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
src/charm.py
tests/unit/fixtures.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_joined.py

Implement the provider side of `fiveg_rfsim` interface: https://github.com/canonical/charm-relation-interfaces/pull/175

feat: Implement fiveg_rfsim interface provider side

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_joined.py

Port number should not be used to constitute  rfsim_address. Only pod ip is enough  as 4043 port number is added by workload.

fix: remove port number from rfsim relation data

---

terraform/terraform.tf

Fixes a problem with Juju Terraform provider versions incompatibility by allowing using anything >= 0.12.0

fix: Allows using range of versions of the Terraform provider

---

terraform/variables.tf

Changes the default charm channel in the Terraform module from `latest/edge` to `2.1/edge`

fix: Fixes the default charm channel in the Terraform module

---

src/charm.py
src/templates/du.conf.j2
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf
tests/unit/test_charm_configure.py

Updates the configuration to one suggested by upstream that gave better results.
I kept the comments in the file as they are the best documentation we have for now.

fix: Use updated configuration suggested by upstream

---

src/templates/du.conf.j2
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf

Change DU config to use band n77, using 20 MHz of bandwidth around 3925 MHz.
Needs to be merged with canonical/oai-ran-ue-k8s-operator#25.

feat: Use band 77 around 3925 MHz

---

tests/unit/fixtures.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py
tests/unit/test_charm_collect_status.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_joined.py
tests/unit/test_charm_remove.py

Now that scenario testing is built into ops we use ops.testing instead of directly calling scenario. Both have the same API. scenario still needs to be independently installed.

chore: use built-in testing from ops

---

src/templates/du.conf.j2
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf

Change the DU configuration to use 40MHz bandwidth for more speed while testing performance with SD-Core.

feat: Use 40MHz bandwidth by default

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
src/charm.py
tests/unit/fixtures.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_changed.py
tests/unit/test_charm_fiveg_rfsim_relation_joined.py

This PR extends the fiveg_rfsim interface according to https://github.com/canonical/charm-relation-interfaces/pull/202 by putting RFSIM address, SST and SD information to the relation data bag.
- Validates Provider application data before putting the information to the relation data bag
- Removes custom events and only uses standart charm events (relation joined, relation changed) to simplify the implementation
- Expand unit tests for fiveg_rfsim interface
The implementation in the charm depends on fiveg_f1 interface as this interface is used to get the SST and SD data from CU charm. fiveg_rfsim relation should wait until data is  retrieved through fiveg_f1 relation. https://github.com/canonical/oai-ran-du-k8s-operator/pull/58 should be merged.
fiveg_f1 interface can carry multiple PLMNs …

feat: extend fiveg_rfsim interface

---

src/charm.py
tests/integration/test_integration.py

- The integration test is simplified to avoid dependecies with the NMS. `any_charm` (A charm simulates any kind of relation consumer charm to make it easy to write integration tests for relation provider charms) is used.
- `any_charm` mocks the NMS so it implements the  `sdcore_config` and `fiveg_core_gnb` in the integration tests.
- The `sdcore_config` and `fiveg_core_gnb` relations were added to `any_charm` [here](https://github.com/canonical/any-charm/pull/31)
- Since a `relation_changed` event is triggered just after `relation_created` event, we can just observe the former.

feat: extend f1 interface integration test

---

charmcraft.yaml
src/charm.py
src/charm_config.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_changed.py

This PR exposes `three-quarter sampling` which is a DU startup command option.
The command line option -E can be used to enable three-quarter sampling for split 8 sample rate. This option might be required for certain radios (e.g., 40MHz with B210).
Enable three-quarter sampling on a running DU:
```
juju config du use-three-quarter-sampling=true
````

feat: expose three quarter sampling rate option

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py

This PR is fixing get_provider_rfsim_information method which is failing if `SD` is not available.
- Get SD optionally
-  Log error messages
- Improve fiveg_rfsim interface requirer tests

fix: fiveg_rfsim lib

---

tests/integration/test_integration.py

nms-mock charm install hook is failing to find `scenario.runtime` which is imported from `ops`. 
This causes failure in integration tests.
The `scenario.runtime`library relies on `ops==2.17.x`.
Latest version of `ops` has breaking changes that make this library incompatible.
As a workaround we need to pin the ops version until incompatibilities are solved in the dependent projects.
Logs that indicate the import issue in the juju debug logs:
```
unit-nms-mock-0: 11:38:56 WARNING unit.nms-mock/0.install   File "/var/lib/juju/agents/unit-nms-mock-0/charm/venv/ops/testing.py", line 181, in <module>
unit-nms-mock-0: 11:38:56 WARNING unit.nms-mock/0.install     import scenario.runtime as _runtime
unit-nms-mock-0: 11:38:56 WARNING unit.nms-mock/0.install ModuleNotFoundError: No module named …
```

fix: scenario.runtime import error in nms-mock charm

---

src/du_parameters/dl_absolute_freq_point_a.py
tests/integration/test_absolute_freq_point_a.py
tests/unit/test_absolute_freq_point_a.py

According to https://docs.google.com/document/d/1f_SPGr5COHTlTbrmJjzYkDrBjvhEeR9XH8JPc8DZa_Q/edit?tab=t.0#heading=h.g8k4gpndinhw, calculate DL AbsoluteFrequencyPointA using Frequency and ARFCN classes.

feat: calculate DL AbsoluteFrequencyPointA

---

src/du_parameters/initial_bwp.py
tests/unit/test_initial_bwp.py

According to https://docs.google.com/document/d/1f_SPGr5COHTlTbrmJjzYkDrBjvhEeR9XH8JPc8DZa_Q/edit?tab=t.0#heading=h.1h3sstuzfc29,  this PR calculates BWPlocationAndBandwidth which depends on Carrier Bandwidth (int type) and Subcarrier Spacing (Frequency type) parameters:
- Total PRB is calculated according Subcarrier Spacing which is given in Table 4 in the spec TE-129. 
- RBstart is zero for initial BWP.
- L is the CarrierBandwith.
Formula:
```
initialBWPlocationAndBandwidth = (Total_PRB *(L-1))+RBstart
```

feat: calculate initial BWP location and Bandwidth

---

charmcraft.yaml
src/charm.py
src/charm_config.py
src/du_parameters/__init__.py
src/du_parameters/absolute_freq_ssb.py
src/du_parameters/carrier_bandwidth.py
src/du_parameters/dl_absolute_freq_point_a.py
src/du_parameters/guard_band.py
src/du_parameters/initial_bwp.py
src/templates/du.conf.j2
tests/integration/test_integration.py
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_multiple_plmns_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf
tests/unit/test_absolute_freq_point_a.py
tests/unit/test_absolute_freq_ssb.py
tests/unit/test_carrier_bandwidth.py
tests/unit/test_charm_collect_status.py
tests/unit/test_charm_config.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_remove.py
tests/unit/test_initial_bwp.py

This PR exposes the following parameters to be used for RAN configuration according to https://docs.google.com/document/d/1f_SPGr5COHTlTbrmJjzYkDrBjvhEeR9XH8JPc8DZa_Q/edit?tab=t.0. This PR does not change the charm code to use new exposed parameters as this is subject to another task and it will be implemented with another PR.
- bandwidth (MHz): the width of radio frequencies, centered on the center frequency 
- center frequency (MHz): the  frequency which is permitted by statutory regulations
- frequency band (prefix of N in FR1 TDD): a frequency range which is defined in FR1 5G spectrum
- subcarrier spacing (KHz): the distance between two adjacent subcarriers
Validations:
- Each parameter is validated according to acceptable values or ranges
- Frequency band uplink/downlink frequency is …

feat: expose config options for RAN configuration

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
src/charm.py
src/du_parameters/frequency.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rfsim_relation_changed.py
tests/unit/test_frequency.py

Implements possibility of passing UE simulator startup params over the fiveg_rfsim relation.
All parameters required by the UE simulator are now taken directly from the DU config file or calculated based on the DU configuration and pushed to the `fiveg_rfsim` relation data bag.

feat: Implements possibility of passing UE simulator startup params over the fiveg_rfsim relation

---

.github/workflows/main.yaml

Fixes the main GH Action workflow to publish `fiveg_rfsim` library

fix: Publishes fiveg_rfsim charm library

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py

Handles empty `fiveg_rfsim` api version

fix: Handles empty fiveg_rfsim api version

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rfsim_requirer_interface.py

Adds `fiveg_rfsim` requirer method for setting the App relation data. It should be used by the Requirer to push the API version to the relation data bag.

chore: Adds fiveg_rfsim requirer method for setting the App relation data

---

lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py

Bumps fiveg_rfsim lib version. I missed that in #94

fix: Bumps fiveg_rfsim lib version

---

.github/workflows/issues.yaml
.github/workflows/main.yaml
.github/workflows/promote.yaml
.github/workflows/tics.yaml
.github/workflows/update-libs.yaml
tox.ini

Adds a TiCS static analysis workflow to run every week, which is the maximum frequency recommend.
The manual trigger option allows developers to manually trigger the analysis workflow whenever needed.
Besides, this PR adds coverage.xml as an outcome of unit tests as this file is required for TiCS static analysis.

feat: add TICS analysis workflow

---

src/templates/du.conf.j2
tests/unit/resources/expected_config.conf
tests/unit/resources/expected_multiple_plmns_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf

This fixes the Coreset0 configuration when operating on n79. I tested this with the B210 operating on n79 and a Quectel module.

fix: Fix coreset0 configuration on n79

---

charmcraft.yaml
src/charm.py
src/charm_config.py
src/templates/du.conf.j2
tests/unit/resources/expected_mimo_config.conf
tests/unit/resources/expected_multiple_plmns_config.conf
tests/unit/resources/expected_rfsim_mode_config.conf
tests/unit/test_charm_configure.py

Adds support for 2x2 MIMO.
New config option `use_mimo` is now available for enabling MIMO support.

feat: Adds support for 2x2 MIMO

---

.github/workflows/main.yaml
.gitignore
charmcraft.yaml
lib/charms/oai_ran_du_k8s/v0/fiveg_rf_config.py
src/charm.py
terraform/outputs.tf
tests/unit/fixtures.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rf_config_provider_interface.py
tests/unit/lib/charms/oai_ran_du/v0/test_fiveg_rf_config_requirer_interface.py
tests/unit/test_charm_configure.py
tests/unit/test_charm_fiveg_rf_config_relation_changed.py

This PR is part of a fix for [TELCO-1730](https://warthogs.atlassian.net/browse/TELCO-1730).
Changes in this PR will allow passing the RF configuration to the `fiveg_rf_config` requirer (in our case the OAI UE charm) regardless of the DU `simulation-mode` being True or False. 
The relation name no longer suggests using simulated RF medium.
The `rfsim_address` will only be passed if the `simulation-mode` config is set to True.
This is a breaking change (because of changing the relation name) and we should expect the OAI tutorials to be broken until changes are done on the UE side as well.
[TELCO-1730]: https://warthogs.atlassian.net/browse/TELCO-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Replaces fiveg_rfsim relation with fiveg_rf_config
